version: "3"

services:
  db:
    image: postgres:16.1-alpine3.19
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "kemkas"
      POSTGRES_PASSWORD: "kemkas-dev42"
      
  proxy:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - $HOME/.aspnet/https/kemkas.pem:/etc/nginx/kemkas.pem
      - $HOME/.aspnet/https/kemkas.key:/etc/nginx/kemkas.key