user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    keepalive_timeout  65;

    upstream frontend {
      server frontend:80;
    }

    upstream backend {
      server backend:8080;
    }

    server {
        listen       8000 ssl;
        server_name  localhost;

        ssl_certificate     /etc/nginx/certs/kemkas.pem;
        ssl_certificate_key /etc/nginx/certs/kemkas.key;
        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        location / {
            proxy_pass  http://frontend;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        location /Identity/ {
            proxy_pass_request_headers on;
            proxy_set_header X-Forwarded-For "$proxy_add_x_forwarded_for";
            proxy_set_header X-Forwarded-Proto "$scheme";
            proxy_set_header X-Forwarded-Host "$http_host";
            proxy_pass   http://backend;
        }

        location /api/ {
            proxy_pass_request_headers on;
            proxy_set_header X-Forwarded-For "$proxy_add_x_forwarded_for";
            proxy_set_header X-Forwarded-Proto "$scheme";
            proxy_set_header X-Forwarded-Host "$http_host";
            proxy_pass   http://backend;
        }

        location /signin- {
            proxy_pass_request_headers on;
            proxy_set_header X-Forwarded-For "$proxy_add_x_forwarded_for";
            proxy_set_header X-Forwarded-Proto "$scheme";
            proxy_set_header X-Forwarded-Host "$http_host";
            proxy_pass   http://backend;
        }

        location /lib/ {
            proxy_pass_request_headers on;
            proxy_pass   http://backend;
        }

        location /js/ {
            proxy_pass_request_headers on;
            proxy_pass   http://backend;
        }

        location /css/ {
            proxy_pass_request_headers on;
            proxy_pass   http://backend;
        }

        location /img/ {
            proxy_pass_request_headers on;
            proxy_pass   http://backend;
        }
    }
}
