name: CI compile & test & build

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  docker-be-build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Kemkas.Web/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          load: true
          tags: kemkas/kemkas-be:edge
      - name: Tag container image
        run: |
          docker tag kemkas/kemkas-be:edge registry.digitalocean.com/kemkas/kemkas-be:${GITHUB_SHA::8}
          docker tag kemkas/kemkas-be:edge ghcr.io/${{ github.repository_owner }}/kemkas-be:${GITHUB_SHA::8}
      - name: Push image to Container Registry
        run: |
          docker push registry.digitalocean.com/kemkas/kemkas-be:${GITHUB_SHA::8}
          docker push ghcr.io/${{ github.repository_owner }}/kemkas-be:${GITHUB_SHA::8}
